integration:
    name: Integration Tests (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.8
      fail-fast: false
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/kilip/ros

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install ansible requirements
        run: |
          python -m pip install --upgrade pip 
          pip install wheel
          pip install -r requirements.txt
    
      - name: Install ansible-test requirements
        run: pip install -r test-requirements.txt
      
      - name: creating docker container
        run: docker-compose up -d

      - name: wait for routeros to be ready
        run: |
          sleep 30

      - name: Runs integration test
        run: |
          ansible-test network-integration -v --color --python ${{ matrix.python }}