version: "3"

services:
    routeros:
        container_name: "ansible-kilip-routeros"
        image: kilip/routeros:latest
        privileged: true
        ports: 
            - "8291:8291"
            - "8729:8729"
            - "8728:8728"
            - "10021:21"
            - "10022:22"
            - "10023:23"
            - "10080:80"
            - "10443:443"
        cap_add: 
            - NET_ADMIN
        devices: 
            - /dev/net/tun