# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://www.github.com/kilip/ansible-routeros-generator
#
# ----------------------------------------------------------------------------

from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class WirelessConnectListResource(ResourceBase):
    resource_name = "wireless_connect_list"
    command = "/interface wireless connect-list"
    gather_network_resources = ["wireless_connect_list"]
    keys = ["name"]
    type = "config"
    argument_spec = {
        "state": {
            "choices": ["merged", "replaced", "overridden", "deleted"],
            "default": "merged",
            "type": "str",
        },
        "config": {
            "elements": "dict",
            "type": "list",
            "options": {
                "3gpp": {"type": "str"},
                "area_prefix": {"type": "str"},
                "comment": {"type": "str"},
                "connect": {
                    "type": "str",
                    "choices": ["no", "yes"],
                    "default": "yes",
                },
                "disabled": {
                    "type": "str",
                    "choices": ["no", "yes"],
                    "default": "no",
                },
                "interface": {"type": "str", "required": True},
                "mac_address": {"type": "str", "default": "00:00:00:00:00:00"},
                "name": {"type": "", "required": True},
                "security_profile": {"type": "str", "default": "none"},
                "signal_range": {"type": "str", "default": "-120..120"},
                "ssid": {"type": "str", "default": ""},
                "wireless_protocol": {
                    "type": "str",
                    "choices": ["802.11", "any", "nstreme", "tdma"],
                    "default": "any",
                },
            },
        },
    }
