# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://github.com/kilip/ansible-routeros-generator
#
# ----------------------------------------------------------------------------
from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class WirelessCapResource(ResourceBase):
    resource_name = "wireless_cap"
    command = "/interface wireless cap"
    gather_network_resources = ["wireless_cap"]
    keys = []
    config_type = "setting"
    supports = ["facts_verbose_mode"]
    argument_spec = {
        "state": {
            "choices": ["present", "reset"],
            "default": "present",
            "type": "str",
        },
        "config": {
            "type": "dict",
            "options": {
                "bridge": {"type": "str", "default": "none"},
                "caps_man_addresses": {"type": "list", "elements": "str"},
                "caps_man_certificate_common_names": {
                    "type": "list",
                    "elements": "str",
                },
                "caps_man_names": {"type": "list", "elements": "str"},
                "certificate": {"type": "str", "default": "none"},
                "discovery_interfaces": {"type": "list", "elements": "str"},
                "enabled": {
                    "type": "str",
                    "choices": ["no", "yes"],
                    "default": "no",
                },
                "interfaces": {"type": "list", "elements": "str"},
                "static_virtual": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": "no",
                },
            },
        },
    }
