# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://github.com/kilip/routeros-generator
#
# ----------------------------------------------------------------------------
from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ...base import ResourceBase


class WirelessCapResource(ResourceBase):
    resource_name = "wireless_cap"
    command = "/interface wireless cap"
    gather_network_resources = ["wireless_cap"]
    keys = ["name"]
    config_type = "setting"
    supports = ["export-verbose-mode"]
    argument_spec = {
        "state": {
            "type": "str",
            "choices": ["present", "reset"],
            "default": "present",
        },
        "config": {
            "type": "dict",
            "options": {
                "bridge": {"type": "str"},
                "caps_man_addresses": {"type": "list"},
                "caps_man_certificate_common_names": {"type": "list"},
                "caps_man_names": {"type": "list"},
                "certificate": {"type": "str"},
                "discovery_interfaces": {"type": "list"},
                "enabled": {"type": "bool", "default": False},
                "interfaces": {"type": "list"},
                "lock_to_caps_man": {"type": "bool", "default": False},
                "static_virtual": {"type": "bool", "default": False},
            },
        },
    }
