# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://www.github.com/kilip/ansible-routeros-generator
#
# ----------------------------------------------------------------------------

from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class CapsmanConfigurationResource(ResourceBase):
    resource_name = "capsman_configuration"
    command = "/caps-man configuration"
    gather_network_resources = ["capsman_configuration"]
    keys = ["name"]
    config_type = "config"
    custom_props = {
        "channel_band": {"ros_key": "channel.band"},
        "channel_control_channel_width": {
            "ros_key": "channel.control-channel-width"
        },
        "channel_extension_channel": {"ros_key": "channel.extension-channel"},
        "channel_frequency": {"ros_key": "channel.frequency"},
        "channel_reselect_interval": {"ros_key": "channel.reselect-interval"},
        "channel_save_selected": {"ros_key": "channel.save-selected"},
        "channel_secondary_frequency": {
            "ros_key": "channel.secondary-frequency"
        },
        "channel_skip_dfs_channels": {"ros_key": "channel.skip-dfs-channels"},
        "channel_tx_power": {"ros_key": "channel.tx-power"},
        "channel_width": {"ros_key": "channel.width"},
        "datapath_bridge": {"ros_key": "datapath.bridge"},
        "datapath_bridge_cost": {"ros_key": "datapath.bridge-cost"},
        "datapath_bridge_horizon": {"ros_key": "datapath.bridge-horizon"},
        "datapath_client_to_client_forwarding": {
            "ros_key": "datapath.client-to-client-forwarding"
        },
        "datapath_interface_list": {"ros_key": "datapath.interface-list"},
        "datapath_l2mtu": {"ros_key": "datapath.l2mtu"},
        "datapath_local_forwarding": {"ros_key": "datapath.local-forwarding"},
        "datapath_mtu": {"ros_key": "datapath.mtu"},
        "datapath_openflow_switch": {"ros_key": "datapath.openflow-switch"},
        "datapath_vlan_id": {"ros_key": "datapath.vlan-id"},
        "datapath_vlan_mode": {"ros_key": "datapath.vlan-mode"},
        "rates_basic": {"ros_key": "rates.basic"},
        "rates_ht_basic_mcs": {"ros_key": "rates.ht-basic-mcs"},
        "rates_ht_supported_mcs": {"ros_key": "rates.ht-supported-mcs"},
        "rates_supported": {"ros_key": "rates.supported"},
        "rates_vht_basic_mcs": {"ros_key": "rates.vht-basic-mcs"},
        "rates_vht_supported_mcs": {"ros_key": "rates.vht-supported-mcs"},
        "security_authentication_types": {
            "ros_key": "security.authentication-types"
        },
        "security_disable_pmkid": {"ros_key": "security.disable-pmkid"},
        "security_eap_methods": {"ros_key": "security.eap-methods"},
        "security_eap_radius_accounting": {
            "ros_key": "security.eap-radius-accounting"
        },
        "security_encryption": {"ros_key": "security.encryption"},
        "security_group_encryption": {"ros_key": "security.group-encryption"},
        "security_group_key_update": {"ros_key": "security.group-key-update"},
        "security_passphrase": {"ros_key": "security.passphrase"},
        "security_tls_certificate": {"ros_key": "security.tls-certificate"},
        "security_tls_mode": {"ros_key": "security.tls-mode"},
    }
    supports = ["reset_value"]
    argument_spec = {
        "state": {
            "choices": ["merged", "replaced", "overridden", "deleted"],
            "default": "merged",
            "type": "str",
        },
        "config": {
            "elements": "dict",
            "type": "list",
            "options": {
                "channel": {"type": "str"},
                "channel_band": {
                    "type": "str",
                    "choices": [
                        "2ghz-b",
                        "2ghz-b/g",
                        "2ghz-b/g/n",
                        "2ghz-onlyg",
                        "2ghz-onlyn",
                        "5ghz-a",
                        "5ghz-a/n",
                        "5ghz-a/n/ac",
                        "5ghz-only-ac",
                        "5ghz-onlyn",
                    ],
                },
                "channel_control_channel_width": {
                    "type": "str",
                    "choices": ["10mhz", "20mhz", "40mhz-turbo", "5mhz"],
                },
                "channel_extension_channel": {
                    "type": "str",
                    "choices": [
                        "Ce",
                        "Ceee",
                        "disabled",
                        "eC",
                        "eCee",
                        "eeCe",
                        "eeeC",
                        "xx",
                        "xxxx",
                    ],
                },
                "channel_frequency": {"type": "int"},
                "channel_reselect_interval": {"type": "str"},
                "channel_save_selected": {
                    "type": "str",
                    "choices": ["no", "yes"],
                    "default": "no",
                },
                "channel_secondary_frequency": {"type": "int"},
                "channel_skip_dfs_channels": {
                    "type": "str",
                    "choices": ["no", "yes"],
                    "default": "no",
                },
                "channel_tx_power": {"type": "int"},
                "channel_width": {"type": "str"},
                "comment": {"type": "str"},
                "country": {"type": "str", "default": "no_country_set"},
                "datapath": {"type": "str"},
                "datapath_bridge": {"type": "str"},
                "datapath_bridge_cost": {"type": "int"},
                "datapath_bridge_horizon": {"type": "int"},
                "datapath_client_to_client_forwarding": {
                    "type": "str",
                    "choices": ["no", "yes"],
                    "default": "no",
                },
                "datapath_interface_list": {"type": "str"},
                "datapath_l2mtu": {"type": "str"},
                "datapath_local_forwarding": {
                    "type": "str",
                    "choices": ["no", "yes"],
                    "default": "no",
                },
                "datapath_mtu": {"type": "str"},
                "datapath_openflow_switch": {"type": "str"},
                "datapath_vlan_id": {"type": "int"},
                "datapath_vlan_mode": {
                    "type": "str",
                    "choices": ["use-service-tag", "use-tag"],
                },
                "disconnect_timeout": {"type": "str"},
                "distance": {"type": "str"},
                "frame_lifetime": {"type": "str"},
                "guard_interval": {
                    "type": "str",
                    "choices": ["any", "long"],
                    "default": "any",
                },
                "hide_ssid": {"type": "str", "choices": ["no", "yes"]},
                "hw_protection_mode": {"type": "str"},
                "hw_retries": {"type": "str"},
                "installation": {
                    "type": "str",
                    "choices": ["any", "indoor", "outdoor"],
                    "default": "any",
                },
                "keepalive_frames": {
                    "type": "str",
                    "choices": ["disabled", "enabled"],
                    "default": "enabled",
                },
                "load_balancing_group": {"type": "str"},
                "max_sta_count": {"type": "int"},
                "mode": {"type": "str", "default": "ap"},
                "multicast_helper": {
                    "type": "str",
                    "choices": ["default", "disabled", "full"],
                    "default": "default",
                },
                "name": {"type": "str", "required": True},
                "rates": {"type": "str"},
                "rates_basic": {
                    "type": "str",
                    "choices": [
                        "11Mbps",
                        "11Mbps",
                        "12Mbps",
                        "18Mbps",
                        "1Mbps",
                        "24Mbps",
                        "2Mbps",
                        "36Mbps",
                        "48Mbps",
                        "5.5Mbps",
                        "54Mbps",
                        "6Mbps",
                    ],
                },
                "rates_ht_basic_mcs": {
                    "type": "list",
                    "elements": "str",
                    "choices": [
                        "mcs-0",
                        "mcs-1",
                        "mcs-10",
                        "mcs-11",
                        "mcs-12",
                        "mcs-13",
                        "mcs-14",
                        "mcs-15",
                        "mcs-16",
                        "mcs-17",
                        "mcs-18",
                        "mcs-19",
                        "mcs-2",
                        "mcs-20",
                        "mcs-21",
                        "mcs-22",
                        "mcs-23",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                        "mcs-8",
                        "mcs-9",
                    ],
                    "default": [
                        "mcs-0",
                        "mcs-1",
                        "mcs-2",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                    ],
                },
                "rates_ht_supported_mcs": {
                    "type": "list",
                    "elements": "str",
                    "choices": [
                        "mcs-0",
                        "mcs-1",
                        "mcs-10",
                        "mcs-11",
                        "mcs-12",
                        "mcs-13",
                        "mcs-14",
                        "mcs-15",
                        "mcs-16",
                        "mcs-17",
                        "mcs-18",
                        "mcs-19",
                        "mcs-2",
                        "mcs-20",
                        "mcs-21",
                        "mcs-22",
                        "mcs-23",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                        "mcs-8",
                        "mcs-9",
                    ],
                    "default": [
                        "mcs-0",
                        "mcs-1",
                        "mcs-2",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                        "mcs-8",
                        "mcs-9",
                        "mcs-10",
                        "mcs-11",
                        "mcs-12",
                        "mcs-13",
                        "mcs-14",
                        "mcs-15",
                        "mcs-16",
                        "mcs-17",
                        "mcs-18",
                        "mcs-19",
                        "mcs-20",
                        "mcs-21",
                        "mcs-22",
                        "mcs-23",
                    ],
                },
                "rates_supported": {
                    "type": "str",
                    "choices": [
                        "11Mbps",
                        "11Mbps",
                        "12Mbps",
                        "18Mbps",
                        "1Mbps",
                        "24Mbps",
                        "2Mbps",
                        "36Mbps",
                        "48Mbps",
                        "5.5Mbps",
                        "54Mbps",
                        "6Mbps",
                    ],
                },
                "rates_vht_basic_mcs": {
                    "type": "str",
                    "choices": ["MCS 0-7", "MCS 0-8", "MCS 0-9", "none"],
                    "default": "none",
                },
                "rates_vht_supported_mcs": {
                    "type": "str",
                    "choices": ["MCS 0-7", "MCS 0-8", "MCS 0-9", "none"],
                    "default": "none",
                },
                "rx_chains": {
                    "type": "list",
                    "elements": "int",
                    "choices": [0, 1, 2, 3],
                    "default": [0],
                },
                "security": {"type": "str", "default": "none"},
                "security_authentication_types": {
                    "type": "list",
                    "elements": "str",
                    "choices": ["wpa-psk", "wpa2-psk", "wpa-eap", "wpa2-eap"],
                },
                "security_disable_pmkid": {"type": "str"},
                "security_eap_methods": {
                    "type": "str",
                    "choices": ["eap-tls", "passthrough"],
                },
                "security_eap_radius_accounting": {"type": "str"},
                "security_encryption": {
                    "type": "list",
                    "elements": "str",
                    "choices": ["aes-ccm", "tkip"],
                },
                "security_group_encryption": {
                    "type": "str",
                    "choices": ["aes-ccm", "tkip"],
                    "default": "aes-ccm",
                },
                "security_group_key_update": {"type": "str", "default": "5m"},
                "security_passphrase": {"type": "str"},
                "security_tls_certificate": {
                    "type": "str",
                    "choices": ["name", "none"],
                },
                "security_tls_mode": {
                    "type": "str",
                    "choices": [
                        "dont-verify-certificate",
                        "no-certificates",
                        "verify-certificate",
                        "verify-certificate-with-crl",
                    ],
                },
                "ssid": {"type": "str"},
                "tx_chains": {
                    "type": "list",
                    "elements": "int",
                    "choices": [0, 1, 2, 3],
                    "default": [0],
                },
            },
        },
    }
