# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://github.com/kilip/ansible-routeros-generator
#
# ----------------------------------------------------------------------------
from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class CapsmanProvisioningResource(ResourceBase):
    resource_name = "capsman_provisioning"
    command = "/caps-man provisioning"
    gather_network_resources = ["capsman_provisioning"]
    keys = ["comment"]
    config_type = "config"
    argument_spec = {
        "state": {
            "choices": ["merged", "replaced", "overridden", "deleted"],
            "default": "merged",
            "type": "str",
        },
        "config": {
            "elements": "dict",
            "type": "list",
            "options": {
                "action": {
                    "type": "str",
                    "choices": [
                        "create-disabled",
                        "create-dynamic-enabled",
                        "create-enabled",
                        "none",
                    ],
                    "default": "none",
                },
                "comment": {"type": "str", "required": True},
                "common_name_regexp": {"type": "str"},
                "hw_supported_modes": {
                    "type": "str",
                    "choices": [
                        "a",
                        "a-turbo",
                        "ac",
                        "an",
                        "b",
                        "g",
                        "g-turbo",
                        "gn",
                    ],
                },
                "identity_regexp": {"type": "str"},
                "ip_address_ranges": {"type": "str"},
                "master_configuration": {"type": "str"},
                "name_format": {
                    "type": "str",
                    "choices": [
                        "cap",
                        "identity",
                        "prefix",
                        "prefix-identity",
                    ],
                    "default": "cap",
                },
                "name_prefix": {"type": "str"},
                "radio_mac": {"type": "str", "default": "00:00:00:00:00:00"},
                "slave_configurations": {"type": "list", "elements": "str"},
            },
        },
    }
