# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://github.com/kilip/ansible-routeros-generator
#
# ----------------------------------------------------------------------------
from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class CapsmanDatapathResource(ResourceBase):
    resource_name = "capsman_datapath"
    command = "/caps-man datapath"
    gather_network_resources = ["capsman_datapath"]
    keys = ["name"]
    config_type = "config"
    custom_props = {
        "bridge_cost": {"ros_key": "bridge_cost"},
        "bridge_horizon": {"ros_key": "bridge_horizon"},
        "client_to_client_forwarding": {
            "ros_key": "client_to_client_forwarding"
        },
        "interface_list": {"ros_key": "interface_list"},
        "local_forwarding": {"ros_key": "local_forwarding"},
        "openflow_switch": {"ros_key": "openflow_switch"},
        "vlan_id": {"ros_key": "vlan_id"},
        "vlan_mode": {"ros_key": "vlan_mode"},
    }
    argument_spec = {
        "state": {
            "choices": ["merged", "replaced", "overridden", "deleted"],
            "default": "merged",
            "type": "str",
        },
        "config": {
            "elements": "dict",
            "type": "list",
            "options": {
                "arp": {
                    "type": "str",
                    "choices": [
                        "disabled",
                        "enabled",
                        "proxy-arp",
                        "reply-only",
                    ],
                    "default": "enabled",
                },
                "bridge": {"type": "str"},
                "bridge_cost": {"type": "int"},
                "bridge_horizon": {"type": "int"},
                "client_to_client_forwarding": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": "no",
                },
                "comment": {"type": "str"},
                "interface_list": {"type": "list", "elements": "str"},
                "l2mtu": {"type": "str"},
                "local_forwarding": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": "no",
                },
                "mtu": {"type": "str"},
                "name": {"type": "str", "required": True},
                "openflow_switch": {"type": "str"},
                "vlan_id": {"type": "int"},
                "vlan_mode": {
                    "type": "str",
                    "choices": ["use-service-tag", "use-tag"],
                },
            },
        },
    }
