# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://github.com/kilip/routeros-generator
#
# ----------------------------------------------------------------------------
from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class CapsmanConfigurationResource(ResourceBase):
    resource_name = "capsman_configuration"
    command = "/caps-man configuration"
    gather_network_resources = ["capsman_configuration"]
    keys = ["name"]
    config_type = "config"
    supports = ["reset_value"]
    argument_spec = {
        "state": {
            "type": "str",
            "choices": ["merged", "replaced", "overridden", "deleted"],
            "default": "merged",
        },
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "channel": {"type": "str"},
                "channel_band": {
                    "type": "str",
                    "choices": [
                        "2ghz-b",
                        "2ghz-b/g",
                        "2ghz-b/g/n",
                        "2ghz-onlyg",
                        "2ghz-onlyn",
                        "5ghz-a",
                        "5ghz-a/n",
                        "5ghz-a/n/ac",
                        "5ghz-only-ac",
                        "5ghz-onlyn",
                    ],
                },
                "channel_control_channel_width": {
                    "type": "str",
                    "choices": ["10mhz", "20mhz", "40mhz-turbo", "5mhz"],
                },
                "channel_extension_channel": {
                    "type": "str",
                    "choices": [
                        "Ce",
                        "Ceee",
                        "disabled",
                        "eC",
                        "eCee",
                        "eeCe",
                        "eeeC",
                        "xx",
                        "xxxx",
                    ],
                },
                "channel_frequency": {"type": "int"},
                "channel_reselect_interval": {"type": "str"},
                "channel_save_selected": {"type": "bool", "default": False},
                "channel_secondary_frequency": {"type": "int", "default": 0},
                "channel_skip_dfs_channels": {
                    "type": "bool",
                    "default": False,
                },
                "channel_tx_power": {"type": "int"},
                "channel_width": {"type": "str"},
                "comment": {"type": "str"},
                "country": {"type": "str", "default": "no_country_set"},
                "datapath": {"type": "str"},
                "datapath_bridge": {"type": "str"},
                "datapath_bridge_cost": {"type": "int"},
                "datapath_bridge_horizon": {"type": "int"},
                "datapath_client_to_client_forwarding": {
                    "type": "bool",
                    "default": False,
                },
                "datapath_interface_list": {"type": "str"},
                "datapath_l2mtu": {"type": "str"},
                "datapath_local_forwarding": {
                    "type": "bool",
                    "default": False,
                },
                "datapath_mtu": {"type": "str"},
                "datapath_openflow_switch": {"type": "str"},
                "datapath_vlan_id": {"type": "int"},
                "datapath_vlan_mode": {
                    "type": "str",
                    "choices": ["use-service-tag", "use-tag"],
                },
                "disabled": {"type": "bool", "default": False},
                "disconnect_timeout": {"type": "str"},
                "distance": {"type": "str"},
                "frame_lifetime": {"type": "str"},
                "guard_interval": {
                    "type": "str",
                    "choices": ["any", "long"],
                    "default": "any",
                },
                "hide_ssid": {"type": "bool"},
                "hw_protection_mode": {"type": "str"},
                "hw_retries": {"type": "str"},
                "installation": {
                    "type": "str",
                    "choices": ["any", "indoor", "outdoor"],
                    "default": "any",
                },
                "keepalive_frames": {
                    "type": "str",
                    "choices": ["disabled", "enabled"],
                    "default": "enabled",
                },
                "load_balancing_group": {"type": "str"},
                "max_sta_count": {"type": "int"},
                "mode": {"type": "str", "default": "ap"},
                "multicast_helper": {
                    "type": "str",
                    "choices": ["default", "disabled", "full"],
                    "default": "default",
                },
                "name": {"type": "str", "required": True},
                "rates": {"type": "str"},
                "rates_basic": {
                    "type": "str",
                    "choices": [
                        "11Mbps",
                        "11Mbps",
                        "12Mbps",
                        "18Mbps",
                        "1Mbps",
                        "24Mbps",
                        "2Mbps",
                        "36Mbps",
                        "48Mbps",
                        "5.5Mbps",
                        "54Mbps",
                        "6Mbps",
                    ],
                },
                "rates_ht_basic_mcs": {
                    "type": "list",
                    "choices": [
                        "mcs-0",
                        "mcs-1",
                        "mcs-10",
                        "mcs-11",
                        "mcs-12",
                        "mcs-13",
                        "mcs-14",
                        "mcs-15",
                        "mcs-16",
                        "mcs-17",
                        "mcs-18",
                        "mcs-19",
                        "mcs-2",
                        "mcs-20",
                        "mcs-21",
                        "mcs-22",
                        "mcs-23",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                        "mcs-8",
                        "mcs-9",
                    ],
                    "default": [
                        "mcs-0",
                        "mcs-1",
                        "mcs-2",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                    ],
                },
                "rates_ht_supported_mcs": {
                    "type": "list",
                    "choices": [
                        "mcs-0",
                        "mcs-1",
                        "mcs-10",
                        "mcs-11",
                        "mcs-12",
                        "mcs-13",
                        "mcs-14",
                        "mcs-15",
                        "mcs-16",
                        "mcs-17",
                        "mcs-18",
                        "mcs-19",
                        "mcs-2",
                        "mcs-20",
                        "mcs-21",
                        "mcs-22",
                        "mcs-23",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                        "mcs-8",
                        "mcs-9",
                    ],
                    "default": [
                        "mcs-0",
                        "mcs-1",
                        "mcs-2",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                        "mcs-8",
                        "mcs-9",
                        "mcs-10",
                        "mcs-11",
                        "mcs-12",
                        "mcs-13",
                        "mcs-14",
                        "mcs-15",
                        "mcs-16",
                        "mcs-17",
                        "mcs-18",
                        "mcs-19",
                        "mcs-20",
                        "mcs-21",
                        "mcs-22",
                        "mcs-23",
                    ],
                },
                "rates_supported": {
                    "type": "str",
                    "choices": [
                        "11Mbps",
                        "11Mbps",
                        "12Mbps",
                        "18Mbps",
                        "1Mbps",
                        "24Mbps",
                        "2Mbps",
                        "36Mbps",
                        "48Mbps",
                        "5.5Mbps",
                        "54Mbps",
                        "6Mbps",
                    ],
                },
                "rates_vht_basic_mcs": {
                    "type": "str",
                    "choices": ["MCS 0-7", "MCS 0-8", "MCS 0-9", "none"],
                },
                "rates_vht_supported_mcs": {
                    "type": "str",
                    "choices": ["MCS 0-7", "MCS 0-8", "MCS 0-9", "none"],
                },
                "rx_chains": {
                    "type": "list",
                    "choices": [0, 1, 2, 3],
                    "default": "a:1:{i:0;i:0;}",
                },
                "security": {"type": "str"},
                "security_authentication_types": {
                    "type": "list",
                    "choices": ["wpa-psk", "wpa2-psk", "wpa-eap", "wpa2-eap"],
                },
                "security_disable_pmkid": {"type": "str"},
                "security_eap_methods": {
                    "type": "str",
                    "choices": ["eap-tls", "passthrough"],
                },
                "security_eap_radius_accounting": {"type": "str"},
                "security_encryption": {
                    "type": "list",
                    "choices": ["aes-ccm", "tkip"],
                },
                "security_group_encryption": {
                    "type": "str",
                    "choices": ["aes-ccm", "tkip"],
                    "default": "aes-ccm",
                },
                "security_group_key_update": {"type": "str", "default": "5m"},
                "security_passphrase": {"type": "str"},
                "security_tls_certificate": {
                    "type": "str",
                    "choices": ["name", "none"],
                },
                "security_tls_mode": {
                    "type": "str",
                    "choices": [
                        "dont-verify-certificate",
                        "no-certificates",
                        "verify-certificate",
                        "verify-certificate-with-crl",
                    ],
                },
                "ssid": {"type": "str"},
                "tx_chains": {
                    "type": "list",
                    "choices": [0, 1, 2, 3],
                    "default": "a:1:{i:0;i:0;}",
                },
            },
        },
    }
