# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://github.com/kilip/routeros-generator
#
# ----------------------------------------------------------------------------
from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class CapsmanAaaResource(ResourceBase):
    resource_name = "capsman_aaa"
    command = "/caps-man aaa"
    gather_network_resources = ["capsman_aaa"]
    keys = ["name"]
    config_type = "setting"
    supports = ["export-verbose-mode"]
    argument_spec = {
        "state": {
            "type": "str",
            "choices": ["present", "reset"],
            "default": "present",
        },
        "config": {
            "type": "dict",
            "options": {
                "called_format": {
                    "type": "str",
                    "choices": ["mac", "mac:ssid", "ssid"],
                    "default": "mac:ssid",
                },
                "interim_update": {"type": "str", "default": "disabled"},
                "mac_caching": {"type": "str", "default": "disabled"},
                "mac_format": {"type": "str", "default": "XX:XX:XX:XX:XX:XX"},
                "mac_mode": {
                    "type": "str",
                    "choices": ["as-username", "as-username-and-password"],
                },
            },
        },
    }
