from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class CapsmanConfigurationResource(ResourceBase):
    resource_name = "capsman_configuration"
    command_root = "/caps-man configuration"
    related_resources = []
    gather_network_resources = ["capsman_configuration"]
    resource_keys = ["name"]
    config_type = "plural"
    key_prefixes = ["channel", "datapath", "rates", "security"]
    argument_spec = {
        "running_config": {"type": "str"},
        "state": {
            "choices": ["merged", "replaced", "deleted", "overridden"],
            "default": "merged",
            "type": "str",
        },
        "config": {
            "elements": "dict",
            "type": "list",
            "options": {
                "security_encryption": {
                    "type": "list",
                    "elements": "str",
                    "choices": ["aes-ccm", "tkip"],
                    "default": None,
                },
                "channel": {"type": "str"},
                "channel_band": {
                    "type": "str",
                    "choices": [
                        "2ghz-b",
                        "2ghz-b/g",
                        "2ghz-b/g/n",
                        "2ghz-onlyg",
                        "2ghz-onlyn",
                        "5ghz-a",
                        "5ghz-a/n",
                        "5ghz-onlyn",
                        "5ghz-a/n/ac",
                        "5ghz-only-ac",
                    ],
                    "default": None,
                },
                "channel_control_channel_width": {
                    "type": "str",
                    "choices": ["40mhz-turbo", "20mhz", "10mhz", "5mhz"],
                    "default": None,
                },
                "channel_extension_channel": {
                    "type": "str",
                    "choices": [
                        "ce",
                        "ceee",
                        "ec",
                        "ecee",
                        "eece",
                        "eeec",
                        "xx",
                        "xxxx",
                        "disabled",
                    ],
                    "default": None,
                },
                "channel_frequency": {"type": "int"},
                "channel_reselect_interval": {"type": "str"},
                "channel_save_selected": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": "no",
                },
                "channel_secondary_frequency": {
                    "type": "str",
                    "default": "auto",
                },
                "channel_skip_dfs_channels": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": "no",
                },
                "channel_tx_power": {"type": "int"},
                "channel_width": {"type": "str"},
                "comment": {"type": "str"},
                "country": {
                    "type": "str",
                    "choices": [
                        "name",
                        "of",
                        "the",
                        "country",
                        "no_country_set",
                    ],
                    "default": "no_country_set",
                },
                "datapath": {"type": "str"},
                "datapath_bridge": {"type": "str"},
                "datapath_bridge_cost": {"type": "int"},
                "datapath_bridge_horizon": {"type": "int"},
                "datapath_client_to_client_forwarding": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": "no",
                },
                "datapath_interface_list": {"type": "str"},
                "datapath_l2mtu": {"type": "str"},
                "datapath_local_forwarding": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": "no",
                },
                "datapath_mtu": {"type": "str"},
                "datapath_openflow_switch": {"type": "str"},
                "datapath_vlan_id": {"type": "int"},
                "datapath_vlan_mode": {
                    "type": "str",
                    "choices": ["use-service-tag", "use-tag"],
                    "default": None,
                },
                "disconnect_timeout": {"type": "str"},
                "distance": {"type": "str"},
                "frame_lifetime": {"type": "str"},
                "guard_interval": {
                    "type": "str",
                    "choices": ["any", "long"],
                    "default": "any",
                },
                "hide_ssid": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": None,
                },
                "hw_protection_mode": {"type": "str"},
                "hw_retries": {"type": "str"},
                "installation": {
                    "type": "str",
                    "choices": ["any", "indoor", "outdoor"],
                    "default": "any",
                },
                "keepalive_frames": {
                    "type": "str",
                    "choices": ["enabled", "disabled"],
                    "default": "enabled",
                },
                "load_balancing_group": {"type": "str"},
                "max_sta_count": {"type": "int"},
                "mode": {"type": "str", "default": "ap"},
                "multicast_helper": {
                    "type": "str",
                    "choices": ["default", "disabled", "full"],
                    "default": "default",
                },
                "name": {"type": "str", "required": True},
                "rates": {"type": "str"},
                "rates_basic": {
                    "type": "str",
                    "choices": [
                        "1mbps",
                        "2mbps",
                        "5.5mbps",
                        "6mbps",
                        "11mbps",
                        "11mbps",
                        "12mbps",
                        "18mbps",
                        "24mbps",
                        "36mbps",
                        "48mbps",
                        "54mbps",
                    ],
                    "default": None,
                },
                "rates_supported": {
                    "type": "str",
                    "choices": [
                        "1mbps",
                        "2mbps",
                        "5.5mbps",
                        "6mbps",
                        "11mbps",
                        "11mbps",
                        "12mbps",
                        "18mbps",
                        "24mbps",
                        "36mbps",
                        "48mbps",
                        "54mbps",
                    ],
                    "default": None,
                },
                "rates_ht_basic_mcs": {
                    "type": "str",
                    "choices": [
                        "list",
                        "of",
                        "(mcs-0",
                        "mcs-1",
                        "mcs-2",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                        "mcs-8",
                        "mcs-9",
                        "mcs-10",
                        "mcs-11",
                        "mcs-12",
                        "mcs-13",
                        "mcs-14",
                        "mcs-15",
                        "mcs-16",
                        "mcs-17",
                        "mcs-18",
                        "mcs-19",
                        "mcs-20",
                        "mcs-21",
                        "mcs-22",
                        "mcs-23)",
                    ],
                    "default": None,
                },
                "rates_ht_supported_mcs": {
                    "type": "str",
                    "choices": [
                        "list",
                        "of",
                        "(mcs-0",
                        "mcs-1",
                        "mcs-2",
                        "mcs-3",
                        "mcs-4",
                        "mcs-5",
                        "mcs-6",
                        "mcs-7",
                        "mcs-8",
                        "mcs-9",
                        "mcs-10",
                        "mcs-11",
                        "mcs-12",
                        "mcs-13",
                        "mcs-14",
                        "mcs-15",
                        "mcs-16",
                        "mcs-17",
                        "mcs-18",
                        "mcs-19",
                        "mcs-20",
                        "mcs-21",
                        "mcs-22",
                        "mcs-23)",
                    ],
                    "default": None,
                },
                "rates_vht_basic_mcs": {
                    "type": "str",
                    "choices": [
                        "none",
                        "mcs",
                        "0-7",
                        "mcs",
                        "0-8",
                        "mcs",
                        "0-9",
                    ],
                    "default": None,
                },
                "rates_vht_supported_mcs": {
                    "type": "str",
                    "choices": [
                        "none",
                        "mcs",
                        "0-7",
                        "mcs",
                        "0-8",
                        "mcs",
                        "0-9",
                    ],
                    "default": None,
                },
                "rx_chains": {"type": "str"},
                "security": {"type": "str"},
                "security_authentication_types": {"type": "str"},
                "security_disable_pmkid": {"type": "str"},
                "security_eap_methods": {
                    "type": "str",
                    "choices": ["eap-tls", "passthrough"],
                    "default": None,
                },
                "security_eap_radius_accounting": {"type": "str"},
                "security_group_encryption": {
                    "type": "str",
                    "choices": ["aes-ccm", "tkip"],
                    "default": "aes-ccm",
                },
                "security_group_key_update": {"type": "str", "default": "5m"},
                "security_passphrase": {"type": "str"},
                "security_tls_certificate": {
                    "type": "str",
                    "choices": ["none", "name"],
                    "default": None,
                },
                "security_tls_mode": {
                    "type": "str",
                    "choices": [
                        "verify-certificate",
                        "dont-verify-certificate",
                        "no-certificates",
                        "verify-certificate-with-crl",
                    ],
                    "default": None,
                },
                "ssid": {"type": "str"},
                "tx_chains": {"type": "str"},
            },
        },
    }
