# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://github.com/kilip/routeros-generator
#
# ----------------------------------------------------------------------------
from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ...base import ResourceBase


class BridgeSettingsResource(ResourceBase):
    resource_name = "bridge_settings"
    command = "/interface bridge settings"
    gather_network_resources = ["bridge_settings"]
    keys = ["name"]
    config_type = "setting"
    supports = ["export-verbose-mode"]
    argument_spec = {
        "state": {
            "type": "str",
            "choices": ["present", "reset"],
            "default": "present",
        },
        "config": {
            "type": "dict",
            "options": {
                "allow_fast_path": {"type": "bool", "default": True},
                "use_ip_firewall": {"type": "bool", "default": False},
                "use_ip_firewall_for_pppoe": {
                    "type": "bool",
                    "default": False,
                },
                "use_ip_firewall_for_vlan": {"type": "bool", "default": False},
            },
        },
    }
