# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://github.com/kilip/routeros-generator
#
# ----------------------------------------------------------------------------

from __future__ import absolute_import, division, print_function

__metaclass__ = type
from .interface.bridge.bridge import BridgeResource
from .interface.bridge.bridge_port import BridgePortResource
from .interface.bridge.bridge_settings import BridgeSettingsResource
from .capsman.capsman_aaa import CapsmanAaaResource
from .capsman.capsman_channel import CapsmanChannelResource
from .capsman.capsman_configuration import CapsmanConfigurationResource
from .capsman.capsman_datapath import CapsmanDatapathResource
from .capsman.capsman_manager import CapsmanManagerResource
from .capsman.capsman_provisioning import CapsmanProvisioningResource
from .interface.ethernet import EthernetResource
from .interface.interface import InterfaceResource
from .interface.vlan import VlanResource
from .interface.wireless.wireless import WirelessResource
from .interface.wireless.wireless_access_list import WirelessAccessListResource
from .interface.wireless.wireless_cap import WirelessCapResource
from .interface.wireless.wireless_connect_list import (
    WirelessConnectListResource,
)
from .interface.wireless.wireless_security_profiles import (
    WirelessSecurityProfilesResource,
)

RESOURCE_SUBSETS = dict(
    bridge=BridgeResource,
    bridge_port=BridgePortResource,
    bridge_settings=BridgeSettingsResource,
    capsman_aaa=CapsmanAaaResource,
    capsman_channel=CapsmanChannelResource,
    capsman_configuration=CapsmanConfigurationResource,
    capsman_datapath=CapsmanDatapathResource,
    capsman_manager=CapsmanManagerResource,
    capsman_provisioning=CapsmanProvisioningResource,
    ethernet=EthernetResource,
    interface=InterfaceResource,
    vlan=VlanResource,
    wireless=WirelessResource,
    wireless_access_list=WirelessAccessListResource,
    wireless_cap=WirelessCapResource,
    wireless_connect_list=WirelessConnectListResource,
    wireless_security_profiles=WirelessSecurityProfilesResource,
)
