from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class FirewallMangleResource(ResourceBase):
    resource_name = "firewall_mangle"
    command_root = "/ip firewall mangle"
    related_resources = []
    gather_network_resources = ["firewall_mangle"]
    resource_keys = ["name"]
    config_type = "plural"
    argument_spec = {
        "running_config": {"type": "str"},
        "state": {"choices": ["overridden"], "type": "str"},
        "config": {
            "elements": "dict",
            "type": "list",
            "options": {
                "chain": {
                    "type": "str",
                    "required": True,
                    "choices": [
                        "forward",
                        "input",
                        "output",
                        "postrouting",
                        "prerouting",
                    ],
                },
                "out_interface": {"type": "str"},
                "per_connection_classifier": {"type": "str"},
                "time": {"type": "str"},
                "new_ttl": {
                    "type": "string",
                    "choices": ["decrement", "increment", "set"],
                    "default": None,
                },
                "ip_sec_policy": {"type": "str"},
                "ttl": {
                    "type": "str",
                    "choices": [
                        "equal",
                        "greater-than",
                        "less-than",
                        "not-equal",
                    ],
                    "default": None,
                },
                "dst_limit": {"type": "str"},
                "action": {
                    "type": "str",
                    "choices": [
                        "accept",
                        "add-dst-to-address-list",
                        "add-src-to-address-list",
                        "change-dscp",
                        "change-mss",
                        "change-ttl",
                        "clear-df",
                        "fasttrack-connection",
                        "jump",
                        "log",
                        "mark-connection",
                        "mark-packet",
                        "mark-routing",
                        "passthrough",
                        "return",
                        "route",
                        "set-priority",
                        "sniff-pc",
                        "sniff-tzsp",
                        "strip-ipv4-options",
                    ],
                    "default": "accept",
                },
                "address_list": {"type": "str"},
                "address_list_timeout": {
                    "type": "str",
                    "choices": ["none-dynamic", "none-static", "time"],
                    "default": "none-dynamic",
                },
                "comment": {"type": "str"},
                "connection_bytes": {"type": "int"},
                "connection_limit": {"type": "int"},
                "connection_mark": {
                    "type": "str",
                    "choices": ["no-mark", "string"],
                    "default": None,
                },
                "connection_nat_state": {
                    "type": "str",
                    "choices": ["srcnat", "dstnat"],
                    "default": None,
                },
                "connection_rate": {"type": "int"},
                "connection_state": {
                    "type": "str",
                    "choices": ["established", "invalid", "new", "related"],
                    "default": None,
                },
                "connection_type": {
                    "type": "str",
                    "choices": [
                        "ftp",
                        "h323",
                        "irc",
                        "pptp",
                        "quake3",
                        "sip",
                        "tftp",
                    ],
                    "default": None,
                },
                "content": {"type": "str"},
                "dscp": {"type": "int"},
                "dst_address": {"type": "str"},
                "dst_address_list": {"type": "str"},
                "dst_address_type": {
                    "type": "str",
                    "choices": ["unicast", "local", "broadcast", "multicast"],
                    "default": None,
                },
                "dst_port": {"type": "int"},
                "fragment": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": None,
                },
                "hotspot": {
                    "type": "str",
                    "choices": [
                        "auth",
                        "from-client",
                        "http",
                        "local-dst",
                        "to-client",
                    ],
                    "default": None,
                },
                "icmp_options": {"type": "int"},
                "in_bridge_port": {"type": "str"},
                "in_interface": {"type": "str"},
                "ingress_priority": {"type": "int"},
                "ipsec_policy": {
                    "type": "str",
                    "choices": ["in", "ipsec", "none"],
                    "default": None,
                },
                "ipv4_options": {
                    "type": "str",
                    "choices": [
                        "any",
                        "loose-source-routing",
                        "no-record-route",
                        "no-router-alert",
                        "no-source-routing",
                        "no-timestamp",
                        "none",
                        "record-route",
                        "router-alert",
                        "strict-source-routing",
                        "timestamp",
                    ],
                    "default": None,
                },
                "jump_target": {"type": "str"},
                "layer7_protocol": {"type": "str"},
                "limit": {"type": "int"},
                "log_prefix": {"type": "str"},
                "new_connection_mark": {"type": "str"},
                "new_dscp": {"type": "int"},
                "new_mss": {"type": "int"},
                "new_packet_mark": {"type": "str"},
                "new_priority": {
                    "type": "str",
                    "choices": [
                        "integer",
                        "from-dscp",
                        "from-dscp-high-3-bits",
                        "from-ingress",
                    ],
                    "default": None,
                },
                "new_routing_mark": {"type": "str"},
                "nth": {"type": "int"},
                "out_bridge_port": {"type": "str"},
                "packet_mark": {
                    "type": "str",
                    "choices": ["no-mark", "string"],
                    "default": None,
                },
                "packet_size": {"type": "int"},
                "passthrough": {
                    "type": "str",
                    "choices": ["yes", "no"],
                    "default": "yes",
                },
                "port": {"type": "int"},
                "protocol": {"type": "str", "default": "tcp"},
                "psd": {"type": "int"},
                "random": {"type": "int"},
                "routing_mark": {"type": "str"},
                "priority": {"type": "int"},
                "src_address": {"type": "str"},
                "src_address_list": {"type": "str"},
                "src_address_type": {
                    "type": "str",
                    "choices": ["unicast", "local", "broadcast", "multicast"],
                    "default": None,
                },
                "src_port": {"type": "int"},
                "src_mac_address": {"type": "str"},
                "tcp_flags": {
                    "type": "str",
                    "choices": [
                        "ack",
                        "cwr",
                        "ece",
                        "fin",
                        "psh",
                        "rst",
                        "syn",
                        "urg",
                    ],
                    "default": None,
                },
                "tcp_mss": {"type": "int"},
                "tls_host": {"type": "str"},
            },
        },
    }
