# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 Anthonius Munthi
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Ansible RouterOS Module Generator
#     and manual changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://github.com/kilip/routeros-generator
#
# ----------------------------------------------------------------------------
from __future__ import absolute_import, division, print_function

__metaclass__ = type

from ..base import ResourceBase


class InterfaceResource(ResourceBase):
    resource_name = "interface"
    command = "/interface"
    gather_network_resources = ["interface"]
    keys = ["name"]
    config_type = "config"
    supports = ["export-verbose-mode"]
    argument_spec = {
        "state": {"type": "str", "choices": ["merged"], "default": "merged"},
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "comment": {"type": "str"},
                "disabled": {"type": "bool", "default": False},
                "l2mtu": {"type": "str"},
                "mtu": {"type": "str"},
                "name": {"type": "str", "required": True},
            },
        },
    }
