name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  units:
    name: Test Units (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.6
          - 3.7
          - 3.8
        include:
          - python: 3.8
            coverage: true
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/kilip/routeros

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install ansible requirements
        run: |
          python -m pip install --upgrade pip 
          pip install wheel
          pip install -r requirements.txt
    
      - name: Install ansible-test requirements
        run: pip install -r test-requirements.txt

      - name: Enable code coverage
        if: matrix.coverage
        run: echo '::set-env name=COVERAGE::1'

      - name: Run unit tests
        run: | 
          if [[ "$COVERAGE" = '1' ]]; then
            ansible-test units -v --color --python ${{ matrix.python }} --coverage
          else
            ansible-test units -v --color --python ${{ matrix.python }}
          fi

      - name: Generate coverage report.
        if: matrix.coverage
        run: ansible-test coverage xml -v --requirements --group-by command --group-by version

      - uses: codecov/codecov-action@v1
        if: matrix.coverage
        with:
          fail_ci_if_error: false

  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      matrix:
        ansible:
          # It's important that Sanity is tested against all stable-X.Y branches
          # Testing against `devel` may fail as new tests are added.
        # - stable-2.9 # Only if your collection supports Ansible 2.9
          - stable-2.10
          - devel
    runs-on: ubuntu-latest
    steps:

      # ansible-test requires the collection to be in a directory in the form
      # .../ansible_collections/kilip/routeros/

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/kilip/routeros

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # it is just required to run that once as "ansible-test sanity" in the docker image
          # will run on all python versions it supports.
          python-version: 3.8

      # Install the head of the given branch (devel, stable-2.10)
      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Install collection dependencies
        run: |
          ansible-galaxy collection install ansible.netcommon -p .
          ansible-galaxy collection install community.network -p .

      # run ansible-test sanity inside of Docker.
      # The docker container has all the pinned dependencies that are required
      # and all python versions ansible supports.
      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
        working-directory: ./ansible_collections/kilip/routeros